# Tarea_4

* Pregunta 1

In [1]:
x<-c(1,2,3,4,5,6)
sum(is.na(x))
sum(!is.na(x))#es el numero de numeros que son diferentes a NA
c(x,x[-(1:length(x))])
x[length(x) + 1]/length(x)#x[a] donde a no es un entero, ya que no hay posiciones no enteras da NA un not avalible 
sum(x > mean(x)) # es el numero de numeros que son mayores que el promedio

[1] 0

[1] 6

[1] 1 2 3 4 5 6

[1] NA

[1] 3

* Pregunta 2

In [2]:
sinh<-function(x){
  y<-(exp(x)-exp(-x))/2 
  return(y)
}

* Pregunta 3

In [4]:
c<-seq(from=3, to=6, by=0.1)
exp(c)*cos(c)

[1] -19.884531 -22.178753 -24.490697 -26.773182 -28.969238 -31.011186
 [7] -32.819775 -34.303360 -35.357194 -35.862834 -35.687732 -34.685042
[13] -32.693695 -29.538816 -25.032529 -18.975233 -11.157417  -1.362099
[19]  10.632038  25.046705  42.099201  61.996630  84.929067 111.061586
[25] 140.525075 173.405776 209.733494 249.468441 292.486707 338.564378
[31] 387.360340

* Pregunta 4   

In [7]:
paste(rep("vector",30),c(1:30))
paste0(rep("fn",30),c(1:30))

[1] "vector 1"  "vector 2"  "vector 3"  "vector 4"  "vector 5"  "vector 6" 
 [7] "vector 7"  "vector 8"  "vector 9"  "vector 10" "vector 11" "vector 12"
[13] "vector 13" "vector 14" "vector 15" "vector 16" "vector 17" "vector 18"
[19] "vector 19" "vector 20" "vector 21" "vector 22" "vector 23" "vector 24"
[25] "vector 25" "vector 26" "vector 27" "vector 28" "vector 29" "vector 30"

[1] "fn1"  "fn2"  "fn3"  "fn4"  "fn5"  "fn6"  "fn7"  "fn8"  "fn9"  "fn10"
[11] "fn11" "fn12" "fn13" "fn14" "fn15" "fn16" "fn17" "fn18" "fn19" "fn20"
[21] "fn21" "fn22" "fn23" "fn24" "fn25" "fn26" "fn27" "fn28" "fn29" "fn30"

* Pregunta 5   
   La derivada de (cos(x)/sen(x)) que es -csc(x)^2 evaluado en pi/4

In [8]:
DF <- D(expression(cos(x)/sin(x)), "x")
x <- pi/4
eval(DF)

[1] -2

* Pregunta 6

In [9]:
x <- c(0,7,8)
x[0.99999999]#ya que R tiene un nivel de tolerancia para redondear los numeros
x[0.99999999999999999]# este se toma como 1 y da '0'

numeric(0)

[1] 0

* Pregunta 7

In [10]:
rep(0:4,each=5)
rep(1:5,5)

[1] 0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5

* Pregunta 8

In [11]:
i<-(2*c(1:17))/(2*(c(1:17))-1)
h<-cumprod(i)
sum(h)+1

[1] 88.67661

* Pregunta 9

In [12]:
expand.grid(c("C","S"),1:6)

Var1 Var2
1  C    1   
2  S    1   
3  C    2   
4  S    2   
5  C    3   
6  S    3   
7  C    4   
8  S    4   
9  C    5   
10 S    5   
11 C    6   
12 S    6

* Pregunta 10

In [17]:
colores<-c("rojo", "azul" ,"verde","blanco", "negro", "amarillo" )
combn(colores,3)

[,1]  [,2]   [,3]  [,4]     [,5]   [,6]  [,7]     [,8]   [,9]     [,10]   
[1,] rojo  rojo   rojo  rojo     rojo   rojo  rojo     rojo   rojo     rojo    
[2,] azul  azul   azul  azul     verde  verde verde    blanco blanco   negro   
[3,] verde blanco negro amarillo blanco negro amarillo negro  amarillo amarillo
     [,11]  [,12] [,13]    [,14]  [,15]    [,16]    [,17]  [,18]    [,19]   
[1,] azul   azul  azul     azul   azul     azul     verde  verde    verde   
[2,] verde  verde verde    blanco blanco   negro    blanco blanco   negro   
[3,] blanco negro amarillo negro  amarillo amarillo negro  amarillo amarillo
     [,20]   
[1,] blanco  
[2,] negro   
[3,] amarillo

* Pregunta 11

In [22]:
colores<-c("rojo", "azul" ,"verde","blanco", "negro", "amarillo" )
combn(colores,3)
combn(colores,2)
combn(colores,1)

[,1]  [,2]   [,3]  [,4]     [,5]   [,6]  [,7]     [,8]   [,9]     [,10]   
[1,] rojo  rojo   rojo  rojo     rojo   rojo  rojo     rojo   rojo     rojo    
[2,] azul  azul   azul  azul     verde  verde verde    blanco blanco   negro   
[3,] verde blanco negro amarillo blanco negro amarillo negro  amarillo amarillo
     [,11]  [,12] [,13]    [,14]  [,15]    [,16]    [,17]  [,18]    [,19]   
[1,] azul   azul  azul     azul   azul     azul     verde  verde    verde   
[2,] verde  verde verde    blanco blanco   negro    blanco blanco   negro   
[3,] blanco negro amarillo negro  amarillo amarillo negro  amarillo amarillo
     [,20]   
[1,] blanco  
[2,] negro   
[3,] amarillo

[,1] [,2]  [,3]   [,4]  [,5]     [,6]  [,7]   [,8]  [,9]     [,10]  [,11]
[1,] rojo rojo  rojo   rojo  rojo     azul  azul   azul  azul     verde  verde
[2,] azul verde blanco negro amarillo verde blanco negro amarillo blanco negro
     [,12]    [,13]  [,14]    [,15]   
[1,] verde    blanco blanco   negro   
[2,] amarillo negro  amarillo amarillo

[,1] [,2] [,3]  [,4]   [,5]  [,6]    
[1,] rojo azul verde blanco negro amarillo

* Pregunta 12 

In [14]:
x<-0:12
y<-choose(12,x)
z<-rep(1/3,13)^(0:12)
u<-rep(2/3,13)^(12:0)
v<-y*z*u
v #primera tipo
dbinom(0:12,size=12,prob=1/3)#segundo tipo
cumsum(v)
pbinom(0:12,size=12,prob = 1/3)

[1] 7.707347e-03 4.624408e-02 1.271712e-01 2.119520e-01 2.384460e-01
 [6] 1.907568e-01 1.112748e-01 4.768921e-02 1.490288e-02 3.311751e-03
[11] 4.967626e-04 4.516023e-05 1.881676e-06

[1] 7.707347e-03 4.624408e-02 1.271712e-01 2.119520e-01 2.384460e-01
 [6] 1.907568e-01 1.112748e-01 4.768921e-02 1.490288e-02 3.311751e-03
[11] 4.967626e-04 4.516023e-05 1.881676e-06

[1] 0.007707347 0.053951426 0.181122646 0.393074678 0.631520714 0.822277544
 [7] 0.933552360 0.981241568 0.996144445 0.999456196 0.999952958 0.999998118
[13] 1.000000000

[1] 0.007707347 0.053951426 0.181122646 0.393074678 0.631520714 0.822277544
 [7] 0.933552360 0.981241568 0.996144445 0.999456196 0.999952958 0.999998118
[13] 1.000000000

* Pregunta 13

* Pregunta 14

* Pregunta 15

In [15]:
set.seed(50)
xVec<- sample(0:999,250, replace = T)
yVec<- sample(0:999,250, replace = T)